# ──────────────────────────────
# Generic SonarQube configuration (works for NestJS & Next.js)
# ──────────────────────────────

sonar.projectKey=${CI_PROJECT_NAME}
sonar.projectName=${CI_PROJECT_NAME}
sonar.sourceEncoding=UTF-8

# Code source & test directories

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=/*.spec.ts, /*.test.ts, /*.e2e-spec.ts, /*.spec.tsx, /*.test.tsx
sonar.exclusions=dist/,.next/,node_modules/,coverage/,build/,.gitlab-ci.yml

# Unified coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Optional: include test execution results if you use jest-sonar-reporter
# sonar.testExecutionReportPaths=report/test-report.xml
